
#change this so that it doesn't have a postgres

version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: planet_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: planet_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
