services:
  db1:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: Events
      MYSQL_ROOT_HOST: '%'
    volumes:
      - events:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "60000:3306"

volumes:
  events:
